// POST /api/dashboard/replica/approve
//
// Body:
//   { citizenId, trigger?, triggerId?, message?, approvedBy? }
//
// Se `message` vier preenchido, opera no modo "aprovacao manual": registra
// como sent direto.
//
// Se `message` for omitido, chama agente Replica para gerar a mensagem
// baseada no trigger + triggerId (busca complaint/talent associado pra
// montar contexto).

import { db, emitAgentEvent, newId, nowIso, saveDb } from "@/lib/db";
import { badRequest, created, notFound, safeJson } from "@/lib/http";
import { generateReplica } from "@/lib/orchestrator";
import type { ReplicaMessage } from "@/types";

export const dynamic = "force-dynamic";

type Body = {
  citizenId?: string;
  trigger?: ReplicaMessage["trigger"];
  triggerId?: string;
  message?: string;
  approvedBy?: string;
};

export async function POST(req: Request) {
  const body = await safeJson<Body>(req);
  if (!body || !body.citizenId) {
    return badRequest("campo 'citizenId' obrigatorio");
  }
  const citizen = db.citizens.find((c) => c.id === body.citizenId);
  if (!citizen) return notFound("cidadao nao encontrado");

  let messageText = body.message?.trim();

  if (!messageText) {
    // Auto-gera via agent Replica
    const ctx = buildReplicaContext(body);
    messageText = await generateReplica({
      trigger: body.trigger || "manual",
      citizen,
      payload: ctx,
    });
  }

  const replica: ReplicaMessage = {
    id: newId(),
    citizenId: citizen.id,
    trigger: body.trigger || "manual",
    triggerId: body.triggerId,
    message: messageText,
    approvedBy: body.approvedBy,
    status: "sent",
    createdAt: nowIso(),
    sentAt: nowIso(),
  };
  db.replicas.push(replica);
  saveDb();

  emitAgentEvent({
    id: newId(),
    agentName: "Replica",
    citizenId: citizen.id,
    action: `Mensagem enviada para ${citizen.name}`,
    payload: {
      replicaId: replica.id,
      preview: messageText.slice(0, 120),
      approvedBy: body.approvedBy,
      autoGenerated: !body.message,
    },
    timestamp: nowIso(),
  });

  return created(replica);
}

function buildReplicaContext(body: Body): {
  originalText?: string;
  action?: string;
  matches?: { title: string; cost?: string }[];
  protocolNumber?: string;
} {
  if (!body.triggerId) return {};

  if (body.trigger === "talent_matched") {
    const t = db.talents.find((x) => x.id === body.triggerId);
    if (!t) return {};
    return {
      originalText: t.rawInput,
      matches: (t.matches || []).slice(0, 3).map((m) => ({
        title: m.title,
        cost: m.cost,
      })),
      action: "Encontramos caminhos compativeis com seu interesse",
    };
  }

  if (body.trigger === "complaint_resolved") {
    const c = db.complaints.find((x) => x.id === body.triggerId);
    if (!c) return {};
    return {
      originalText: c.rawInput,
      protocolNumber: c.protocolNumber,
      action: c.resolvedAction || "Tomamos providencias sobre seu relato",
    };
  }

  return {};
}
